### Base resource
GET http://localhost:3000

### Get Jobs
GET http://localhost:3000/jobs

### Get Job By Id
GET http://localhost:3000/jobs/63946ddc347a7081365acf69

### Create Job
POST http://localhost:3000/jobs
content-type: application/json

{
    "title": "Systems Architect",
    "company": "Apple"
}

### Update Job
PUT http://localhost:3000/jobs/6393d69f616525079cbc40d3
content-type: application/json

{
    "title": "Sr. Software Engineer",
    "company": "Google"
}

### Delete Job By Id
DELETE http://localhost:3000/jobs/63946ddc347a7081365acf69
