### Base resource
GET http://localhost:3000

### Get Jobs
GET http://localhost:3000/jobs

### Get Job By Id
GET http://localhost:3000/jobs/639469352f012e04ca8a05a1

### Create Job
POST http://localhost:3000/jobs
content-type: application/json

{
    "title": "Systems Architect",
    "company": "Apple"
}

### Update Job
PUT http://localhost:3000/jobs/639469352f012e04ca8a05a1
content-type: application/json

{
    "company": "639472efc099a65d87a8e8a1"
}

### Delete Job By Id
DELETE http://localhost:3000/jobs/63946ddc347a7081365acf69

### Base resource
GET http://localhost:3000

### Get companies
GET http://localhost:3000/companies

### Get Company By Id
GET http://localhost:3000/companies/639472efc099a65d87a8e8a1

### Create Company
POST http://localhost:3000/companies
content-type: application/json

{
    "name": "Google"
}

### Update Company
PUT http://localhost:3000/companies/639472efc099a65d87a8e8a1
content-type: application/json

{
    "name": "Apple Inc."
}

### Delete company By Id
DELETE http://localhost:3000/companies/63947318c099a65d87a8e8a7

